language: java

jdk:
 -openjdk8
script: ant build
addons:
sonarcloud: 
  organization:"riccardoburaioli"
token: 
  secure:"travis encrypt 03670ce9eae98a343580f7f500a7ba8af9a7d10c"
script: 
- ant build 
- sonar-scanner 
 