language: java

jdk:
 -openjdk8

addons:
sonarcloud: 
  organization:"riccardoburaioli"
token: 
  secure:"travis encrypt 32114f5855757e33e7f6adb91ab2b596b03cc3ca"
script: 
- ant build 
- sonar-scanner

 