language: java

jdk:
 -openjdk8

addons:
sonarcloud: 
  organization:"riccardoburaioli"
token: 
  secure:"e4cf5681f0bbce46cc77f4cd4ff06e21b562ee68"
script: 
- ant build 
- sonar-scanner 

 