language: java

jdk:
 -openjdk8
script: ant build
addons:
sonarcloud: 
  organization:"riccardoburaioli"
token: 
  secure:"e4cf5681f0bbce46cc77f4cd4ff06e21b562ee68"
script: 
- ant build 
- sonar-scanner 
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
 